services:
  - type: web
    name: rifa-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rifa-db
          property: connectionString
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: MERCADOPAGO_PUBLIC_KEY
        sync: false
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
      - key: NEXT_PUBLIC_ADMIN_PASSWORD
        sync: false

databases:
  - name: rifa-db
    databaseName: rifa_production
    plan: free